services:
  web:
    image: ghcr.io/nicholasmparker/slackparser:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGO_DB=slack_data
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - FILE_STORAGE=/app/file_storage
      - DATA_DIR=/app/data
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - file_storage:/app/file_storage
      - data:/app/data
    depends_on:
      - mongodb
      - chroma
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  chroma:
    image: chromadb/chroma:latest
    restart: unless-stopped
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    # No built-in healthcheck for Ollama yet
    # We could add a custom one that checks model availability

volumes:
  mongodb_data:
  chroma_data:
  ollama_data:
  file_storage:
  data:
