version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=slack_data
      - OLLAMA_URL=http://host.docker.internal:11434
      - DATA_DIR=/data
      - FILE_STORAGE=/files
      - TEST_MODE=true
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./app:/app/app
      - ./data:/data
      - ./files:/files
      - ./data/uploads:/data/uploads
      - ./data/extracts:/data/extracts
      - ./file_storage:/file_storage
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mongodb:
        condition: service_started
      chroma:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G
    restart: on-failure:3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "6001:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  mongodb_data:
  mongodb_config:
  chroma_data:
