services:
  web:
    build: .
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=${MONGO_DB:-slack_data}
      - OLLAMA_URL=http://host.docker.internal:11434
      - DATA_DIR=/data
      - FILE_STORAGE=/files
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - ./app:/app/app
      - ./data:/data
      - ./files:/files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mongodb:
        condition: service_started
      chroma:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: on-failure:3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  chroma:
    image: chromadb/chroma:0.5.18
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
      - IS_PERSISTENT=true
    healthcheck:
      test: curl -f http://localhost:8000/api/v1/heartbeat || exit 1
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

volumes:
  mongodb_data:
    name: mongodb_data
  mongodb_config:
    name: mongodb_config
  chroma_data:
    name: chroma_data
