version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    volumes:
      - ./data:/data
      - ./file_storage:/file_storage
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: on-failure:3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mongodb_data:
